Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig1 = strain.plot()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m fig1 [38;5;241m=[39m strain[38;5;241m.[39mplot()

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/gwpy/timeseries/core.py:621[0m, in [0;36mTimeSeriesBase.plot[0;34m(self, method, figsize, xscale, **kwargs)[0m
[1;32m    602[0m [38;5;250m[39m[38;5;124;03m"""Plot the data for this timeseries[39;00m
[1;32m    603[0m 
[1;32m    604[0m [38;5;124;03mReturns[39;00m
[0;32m   (...)[0m
[1;32m    618[0m [38;5;124;03m    for documentation of keyword arguments used in rendering the data[39;00m
[1;32m    619[0m [38;5;124;03m"""[39;00m
[1;32m    620[0m kwargs[38;5;241m.[39mupdate(figsize[38;5;241m=[39mfigsize, xscale[38;5;241m=[39mxscale)
[0;32m--> 621[0m [38;5;28;01mreturn[39;00m [38;5;28msuper[39m()[38;5;241m.[39mplot(method[38;5;241m=[39mmethod, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/gwpy/types/series.py:468[0m, in [0;36mSeries.plot[0;34m(self, method, **kwargs)[0m
[1;32m    465[0m     kwargs[38;5;241m.[39msetdefault([38;5;124m'[39m[38;5;124mxlim[39m[38;5;124m'[39m, ([38;5;28mself[39m[38;5;241m.[39mdx[38;5;241m.[39mvalue, [38;5;28mself[39m[38;5;241m.[39mxspan[[38;5;241m1[39m]))
[1;32m    467[0m [38;5;66;03m# make plot[39;00m
[0;32m--> 468[0m plot [38;5;241m=[39m Plot([38;5;28mself[39m, method[38;5;241m=[39mmethod, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    470[0m [38;5;66;03m# set default y-axis label (xlabel is set by Plot())[39;00m
[1;32m    471[0m default_unit_label(plot[38;5;241m.[39mgca()[38;5;241m.[39myaxis, [38;5;28mself[39m[38;5;241m.[39munit)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/gwpy/plot/plot.py:116[0m, in [0;36mPlot.__init__[0;34m(self, *data, **kwargs)[0m
[1;32m    114[0m [38;5;66;03m# initialise axes with data[39;00m
[1;32m    115[0m [38;5;28;01mif[39;00m data [38;5;129;01mor[39;00m kwargs[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mgeometry[39m[38;5;124m"[39m):
[0;32m--> 116[0m     [38;5;28mself[39m[38;5;241m.[39m_init_axes(data, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/gwpy/plot/plot.py:200[0m, in [0;36mPlot._init_axes[0;34m(self, data, method, xscale, sharex, sharey, geometry, separate, **kwargs)[0m
[1;32m    198[0m axes_kw[[38;5;124m"[39m[38;5;124msharey[39m[38;5;124m"[39m] [38;5;241m=[39m shared_with[sharey]
[1;32m    199[0m axes_kw[[38;5;124m'[39m[38;5;124mxscale[39m[38;5;124m'[39m] [38;5;241m=[39m xscale [38;5;28;01mif[39;00m xscale [38;5;28;01melse[39;00m _parse_xscale(group)
[0;32m--> 200[0m ax [38;5;241m=[39m axarr[row, col] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39madd_subplot(gs[row, col], [38;5;241m*[39m[38;5;241m*[39maxes_kw)
[1;32m    202[0m [38;5;66;03m# plot data[39;00m
[1;32m    203[0m plot_func [38;5;241m=[39m [38;5;28mgetattr[39m(ax, method)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py:768[0m, in [0;36madd_subplot[0;34m(self, *args, **kwargs)[0m
[1;32m    765[0m         args [38;5;241m=[39m [38;5;28mtuple[39m([38;5;28mmap[39m([38;5;28mint[39m, [38;5;28mstr[39m(args[[38;5;241m0[39m])))
[1;32m    766[0m     projection_class, pkw [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_process_projection_requirements(
[1;32m    767[0m         [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 768[0m     ax [38;5;241m=[39m projection_class([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mpkw)
[1;32m    769[0m     key [38;5;241m=[39m (projection_class, pkw)
[1;32m    770[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_add_axes_internal(ax, key)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/gwpy/plot/axes.py:168[0m, in [0;36mAxes.__init__[0;34m(self, *args, **kwargs)[0m
[1;32m    166[0m     [38;5;28mself[39m[38;5;241m.[39m_get_lines [38;5;241m=[39m PlotArgsProcessor()
[1;32m    167[0m [38;5;28;01melse[39;00m:
[0;32m--> 168[0m     [38;5;28mself[39m[38;5;241m.[39m_get_lines [38;5;241m=[39m PlotArgsProcessor([38;5;28mself[39m)
[1;32m    170[0m [38;5;66;03m# reset data formatters (for interactive plots) to support[39;00m
[1;32m    171[0m [38;5;66;03m# GPS time display[39;00m
[1;32m    172[0m [38;5;28mself[39m[38;5;241m.[39mfmt_xdata [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_fmt_xdata

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py:217[0m, in [0;36m__init__[0;34m(self, output)[0m
[1;32m    211[0m [38;5;28;01mclass[39;00m [38;5;21;01m_process_plot_var_args[39;00m:
[1;32m    212[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    213[0m [38;5;124;03m    Process variable length arguments to `~.Axes.plot`, to support ::[39;00m
[1;32m    214[0m 
[1;32m    215[0m [38;5;124;03m      plot(t, s)[39;00m
[1;32m    216[0m [38;5;124;03m      plot(t1, s1, t2, s2)[39;00m
[0;32m--> 217[0m [38;5;124;03m      plot(t1, s1, 'ko', t2, s2)[39;00m
[1;32m    218[0m [38;5;124;03m      plot(t1, s1, 'ko', t2, s2, 'r--', t3, e3)[39;00m
[1;32m    219[0m 
[1;32m    220[0m [38;5;124;03m    an arbitrary number of *x*, *y*, *fmt* are allowed[39;00m
[1;32m    221[0m [38;5;124;03m    """[39;00m
[1;32m    222[0m     [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, axes, command[38;5;241m=[39m[38;5;124m'[39m[38;5;124mplot[39m[38;5;124m'[39m):
[1;32m    223[0m         [38;5;28mself[39m[38;5;241m.[39maxes [38;5;241m=[39m axes

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/_api/__init__.py:130[0m, in [0;36mcheck_in_list[0;34m(values, _print_supported_values, **kwargs)[0m
[1;32m    128[0m msg [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mval[38;5;132;01m!r}[39;00m[38;5;124m is not a valid value for [39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    129[0m [38;5;28;01mif[39;00m _print_supported_values:
[0;32m--> 130[0m     msg [38;5;241m+[39m[38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124m; supported values are [39m[38;5;132;01m{[39;00m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;28mmap[39m([38;5;28mrepr[39m,[38;5;250m [39mvalues))[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    131[0m [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(msg)

[0;31mValueError[0m: <Axes: xlabel='Time [$\\mathrm{s}$]'> is not a valid value for output; supported values are 'Line2D', 'Polygon', 'coordinates'

