Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.plot(logTeff[co_core_mask],logL[co_core_mask])
plt.plot(np.log10(Teff_est),np.log10(L_est))
plt.xlim(4.3,3.5)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m plt[38;5;241m.[39mplot(logTeff[co_core_mask],logL[co_core_mask])
[0;32m----> 2[0m plt[38;5;241m.[39mplot(np[38;5;241m.[39mlog10(Teff_est),np[38;5;241m.[39mlog10(L_est))
[1;32m      3[0m plt[38;5;241m.[39mxlim([38;5;241m4.3[39m,[38;5;241m3.5[39m)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/pyplot.py:2812[0m, in [0;36mplot[0;34m(scalex, scaley, data, *args, **kwargs)[0m
[1;32m   2810[0m [38;5;129m@_copy_docstring_and_deprecators[39m(Axes[38;5;241m.[39mplot)
[1;32m   2811[0m [38;5;28;01mdef[39;00m [38;5;21mplot[39m([38;5;241m*[39margs, scalex[38;5;241m=[39m[38;5;28;01mTrue[39;00m, scaley[38;5;241m=[39m[38;5;28;01mTrue[39;00m, data[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m-> 2812[0m     [38;5;28;01mreturn[39;00m gca()[38;5;241m.[39mplot(
[1;32m   2813[0m         [38;5;241m*[39margs, scalex[38;5;241m=[39mscalex, scaley[38;5;241m=[39mscaley,
[1;32m   2814[0m         [38;5;241m*[39m[38;5;241m*[39m({[38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m: data} [38;5;28;01mif[39;00m data [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m {}), [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py:1688[0m, in [0;36mAxes.plot[0;34m(self, scalex, scaley, data, *args, **kwargs)[0m
[1;32m   1445[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m   1446[0m [38;5;124;03mPlot y versus x as lines and/or markers.[39;00m
[1;32m   1447[0m 
[0;32m   (...)[0m
[1;32m   1685[0m [38;5;124;03m(``'green'``) or hex strings (``'#008000'``).[39;00m
[1;32m   1686[0m [38;5;124;03m"""[39;00m
[1;32m   1687[0m kwargs [38;5;241m=[39m cbook[38;5;241m.[39mnormalize_kwargs(kwargs, mlines[38;5;241m.[39mLine2D)
[0;32m-> 1688[0m lines [38;5;241m=[39m [[38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39m_get_lines([38;5;241m*[39margs, data[38;5;241m=[39mdata, [38;5;241m*[39m[38;5;241m*[39mkwargs)]
[1;32m   1689[0m [38;5;28;01mfor[39;00m line [38;5;129;01min[39;00m lines:
[1;32m   1690[0m     [38;5;28mself[39m[38;5;241m.[39madd_line(line)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py:311[0m, in [0;36m_process_plot_var_args.__call__[0;34m(self, data, *args, **kwargs)[0m
[1;32m    309[0m     this [38;5;241m+[39m[38;5;241m=[39m args[[38;5;241m0[39m],
[1;32m    310[0m     args [38;5;241m=[39m args[[38;5;241m1[39m:]
[0;32m--> 311[0m [38;5;28;01myield from[39;00m [38;5;28mself[39m[38;5;241m.[39m_plot_args(
[1;32m    312[0m     this, kwargs, ambiguous_fmt_datakey[38;5;241m=[39mambiguous_fmt_datakey)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py:504[0m, in [0;36m_process_plot_var_args._plot_args[0;34m(self, tup, kwargs, return_kwargs, ambiguous_fmt_datakey)[0m
[1;32m    501[0m     [38;5;28mself[39m[38;5;241m.[39maxes[38;5;241m.[39myaxis[38;5;241m.[39mupdate_units(y)
[1;32m    503[0m [38;5;28;01mif[39;00m x[38;5;241m.[39mshape[[38;5;241m0[39m] [38;5;241m!=[39m y[38;5;241m.[39mshape[[38;5;241m0[39m]:
[0;32m--> 504[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mx and y must have same first dimension, but [39m[38;5;124m"[39m
[1;32m    505[0m                      [38;5;124mf[39m[38;5;124m"[39m[38;5;124mhave shapes [39m[38;5;132;01m{[39;00mx[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m and [39m[38;5;132;01m{[39;00my[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    506[0m [38;5;28;01mif[39;00m x[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m2[39m [38;5;129;01mor[39;00m y[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m2[39m:
[1;32m    507[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mx and y can be no greater than 2D, but have [39m[38;5;124m"[39m
[1;32m    508[0m                      [38;5;124mf[39m[38;5;124m"[39m[38;5;124mshapes [39m[38;5;132;01m{[39;00mx[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m and [39m[38;5;132;01m{[39;00my[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mValueError[0m: x and y must have same first dimension, but have shapes (2, 0) and (0,)

