Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
models = []


models.append(Model(1, profiles=["M1_default_profile8.data",
                                 "M1_default_profile218.data"],
                    history="M1_default_trimmed_history.data"))

models.append(Model(8, profiles=["M8_basic_co_profile8.data",
                                 "M8_basic_co_profile39.data"],
                    history="M8_basic_co_trimmed_history.data"))

models.append(Model(15, profiles=["M15_aprox21_profile8.data",
                                  "M15_aprox21_profile19.data"],
                    history="M15_aprox21_trimmed_history.data"))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 4[0m
[1;32m      1[0m models [38;5;241m=[39m []
[0;32m----> 4[0m models[38;5;241m.[39mappend(Model([38;5;241m1[39m, profiles[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mM1_default_profile8.data[39m[38;5;124m"[39m,
[1;32m      5[0m                                  [38;5;124m"[39m[38;5;124mM1_default_profile218.data[39m[38;5;124m"[39m],
[1;32m      6[0m                     history[38;5;241m=[39m[38;5;124m"[39m[38;5;124mM1_default_trimmed_history.data[39m[38;5;124m"[39m))
[1;32m      8[0m models[38;5;241m.[39mappend(Model([38;5;241m8[39m, profiles[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mM8_basic_co_profile8.data[39m[38;5;124m"[39m,
[1;32m      9[0m                                  [38;5;124m"[39m[38;5;124mM8_basic_co_profile39.data[39m[38;5;124m"[39m],
[1;32m     10[0m                     history[38;5;241m=[39m[38;5;124m"[39m[38;5;124mM8_basic_co_trimmed_history.data[39m[38;5;124m"[39m))
[1;32m     12[0m models[38;5;241m.[39mappend(Model([38;5;241m15[39m, profiles[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mM15_aprox21_profile8.data[39m[38;5;124m"[39m,
[1;32m     13[0m                                   [38;5;124m"[39m[38;5;124mM15_aprox21_profile19.data[39m[38;5;124m"[39m],
[1;32m     14[0m                     history[38;5;241m=[39m[38;5;124m"[39m[38;5;124mM15_aprox21_trimmed_history.data[39m[38;5;124m"[39m))

Cell [0;32mIn[2], line 5[0m, in [0;36mModel.__init__[0;34m(self, mass, profiles, history)[0m
[1;32m      3[0m [38;5;28mself[39m[38;5;241m.[39mmass [38;5;241m=[39m mass
[1;32m      4[0m [38;5;28;01mif[39;00m history:
[0;32m----> 5[0m     [38;5;28mself[39m[38;5;241m.[39mhistory [38;5;241m=[39m mr[38;5;241m.[39mMesaData(history)
[1;32m      6[0m [38;5;28mself[39m[38;5;241m.[39mprofiles [38;5;241m=[39m []
[1;32m      7[0m [38;5;28;01mif[39;00m profiles:

[0;31mNameError[0m: name 'mr' is not defined

